### ISSUE TITLE
Crash on replace compose screen

### ISSUE THREAD

**Issue by maqsats** [icerockdev/moko-biometry#28]
Cannot replace compose screen when I launch Biometry

`java.lang.IllegalStateException: **no event up from DESTROYED**
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:250)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
                                                                                                    	at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner.onStop(AndroidScreenLifecycleOwner.kt:110)
                                                                                                    	at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner.access$onStop(AndroidScreenLifecycleOwner.kt:44)
                                                                                                    	at cafe.adriel.voyager.androidx.AndroidScreenLifecycleOwner$LifecycleDisposableEffect$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:485)
                                                                                                    	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:87)
                                                                                                    	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1264)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:975)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:996)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:636)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:548)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher`

**Comment by maqsats** [comment]
![image](https://github.com/icerockdev/moko-biometry/assets/49427678/ade1dc54-22af-4071-99a6-ea2c1b81952b)
I am calling removeObserver onDestroy and logs show that everything works correctly

**Comment by maqsats** [comment]
@Dorofeev @YokiToki @Alex009 @Tetraquark
